### ISSUE TITLE
Little issue in the encode method of LineCodec

### ISSUE THREAD

**Issue by Kerollmops** [tokio-rs/tokio-line#25]
You [reserve additional `len` to the BytesMut buffer](https://github.com/tokio-rs/tokio-line/blob/master/multiplexed/src/lib.rs#L205) but you take the `buf.len()` and not the `msg.1.len()` (The String/Payload `len`).

**Comment by carllerche** [comment]
Ah, good catch. I'd love a PR for that :)

**Comment by Kerollmops** [comment]
whoops, didn't see this message, thanks @creativcoder and sorry for that @carllerche
