### ISSUE TITLE
Fails to build since pull request #4

### ISSUE THREAD

**Issue by nbigaouette** [tokio-rs/tokio-line#5]
Pull request #4 (08a22bb03ae8882503e8ff126864e081b9292018) introduced made some changes which break compilation:

```
cargo build
   Compiling tokio-line v0.1.0 (file:///tmp/tokio-line.git)
src/client.rs:14:12: 14:77 error: type name `pipeline::Client` is undefined or not in scope [E0412]
src/client.rs:14     inner: pipeline::Client<String, String, Empty<(), io::Error>, io::Error>,
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/client.rs:14:12: 14:77 help: run `rustc --explain E0412` to see a detailed explanation
src/client.rs:14:12: 14:77 help: you can import it into scope: `use client::Client;`.
error: aborting due to previous error
error: Could not compile `tokio-line`.

To learn more, run the command again with --verbose.
```

Note: Using tokio tokio-rs/tokio-proto@d282450a6d5e491bb98e1b971bc0e80fc445c1cb (before the rename to tokio-proto).

**Comment by SirVer** [comment]
This has nothing todo with my pull request #4 though - it seems like @alexcrichton is pulling tokio into smaller repos doing a ton of refactoring. For example it looks like reactor is gone from Tokio - I guess the futures reactor is now used. I just tried my hands for a few minutes on fixing tokio-line, but the changes are pretty widespread and I could not track all down or even understand them all. 

It seems that the total numbers of concepts is going down, which is good. It also seems like the number of moving parts (i.e. repositories) is going up - so it becomes harder to get started with Tokio. I sure hope we get a few more tutorials soon to make this better :).

I guess we have to wait until @carllerche or @alexcrichton fix the examples again.

**Comment by carllerche** [comment]
It should work again now :)
